
// scene name: War
var subTitle =  'West Point, New York, June, 1783';
tabTexts  = new Object();
rollTexts = new Object();
rollLinks = new Object();

  tabTexts["Overview"] = ['<b>Overview</b>' ,'<p><b>Peace at Last</b><br>The war for independence was all but won by 1783. Soldiers and civilians alike rejoiced. The army could be disbanded; officers and enlisted men could go home.  The bad news was that eight exhausting years of conflict had left the United States with an empty treasury and a staggering <a href="javascript:glossary(&apos;war_debt&apos;)"><font color="#660000"><u>war debt</u></font></a>.  How would the government pay the long-overdue money it owed to the soldiers of the <a href="javascript:glossary(&apos;continental_army&apos;)"><font color="#660000"><u>Continental Army</u></font></a>, let alone the special <a href="javascript:glossary(&apos;bounty&apos;)"><font color="#660000"><u>bounties</u></font></a> and other reenlistment incentives so liberally offered during the darkest hours of the war? </p><br><p><b>A Precarious Situation</b><br>Entire Continental regiments had mutinied over the lack of pay during the war. Now, some officers wanted to march the whole army to Philadelphia. They argued that only the threat of force would prevent Congress from abandoning its promise to provide Continental officers half pay <a href="javascript:glossary(&apos;pension&apos;)"><font color="#660000"><u>pensions</u></font></a> for life once the war ended. A moving address by Commander-in-Chief George Washington in March, 1783, defused this so-called <a href="javascript:glossary(&apos;newburgh_conspiracy&apos;)"><font color="#660000"><u>Newburgh Conspiracy</u></font></a>, but the situation remained precarious. The government shifted its attention to dispersing the angry, still unpaid rank and file. </p><br><p><b>Emergency Measures</b><br>Congress decided to <a href="javascript:glossary(&apos;furlough&apos;)"><font color="#660000"><u>furlough</u></font></a> rather than discharge most of the army in the months leading up to the ratification of the peace treaty. Entire regiments marched to their home states under the tight control of their officers. An emergency loan enabled the government to give each soldier one month&apos;s pay in cash. Each man received the remainder of his back pay in government certificates redeemable for cash, plus interest at a future date. At General Washington&apos;s suggestion, soldiers were permitted to keep their uniforms, muskets and other army-issued equipment. Lacking decent clothing, food and other necessities, many men quickly spent what little cash they received and sold their certificates, muskets and other possessions to support themselves and their families. Only a few regiments remained under arms at <a href="javascript:artifact(&apos;west_point&apos;)"><font color="#660000"><u>West Point</u></font></a>, New York, when Congress began formally discharging the entire army in the fall of 1783. </p><br>'];
  tabTexts["Government"] = ['<b>Government</b>' ,'<p><b>A Dangerous Situation</b><br>The end of the war was in sight by 1783, and not a moment too soon. The United States treasury was empty. Congress needed to shed the costly burden of maintaining the <a href="javascript:glossary(&apos;continental_army&apos;)"><font color="#660000"><u>Continental Army</u></font></a> as soon as possible. Yet, how could Congress peaceably disband these soldiers when it lacked the means to pay them? Whole regiments had rioted and even mutinied over the lack of pay and other perceived grievances during the war. Discharging officers and enlisted men without giving them their back pay, pensions and bonuses could spark a full scale uprising.  </p><br><p><b>Promises to Pay</b><br>Superintendent of Finance Robert Morris managed to negotiate a hasty cash loan that would put one month&apos;s pay in the soldiers&apos; pockets. The remainder of their pay would be issued in government <a href="javascript:glossary(&apos;scrip&apos;)"><font color="#660000"><u>scrip</u></font></a> that could be redeemed for cash at a later date. The government also generously allowed soldiers to keep their army-issued <a href="javascript:artifact(&apos;charleville_musket&apos;)"><font color="#660000"><u>weapons</u></font></a>, uniforms and <a href="javascript:artifact(&apos;pot_iron&apos;)"><font color="#660000"><u>equipment</u></font></a>.</p><br><p><b>Crisis Averted</b><br>Congress decided to furlough most of the men, rather than discharge them. After all, the peace treaty had not yet been finalized. The British army still occupied New York City; the army might be needed again. Regiments marched home under military discipline, thus preventing any disgruntled, ill-disciplined soldiers from looting the countryside or marching on Congress. Once they were safely dispersed, Congress issued official discharges to these men. The few remaining regiments stationed at <a href="javascript:artifact(&apos;west_point&apos;)"><font color="#660000"><u>West Point</u></font></a>, New York, were discharged over the summer and fall. By the winter of 1783, the army was safely disbanded, and Congress had averted a serious crisis.</p><br>'];
  tabTexts["Army"] = ['<b>Army</b>' ,'<p><b>Peace?</b><br>Rumors of peace raced through the <a href="javascript:glossary(&apos;continental_army&apos;)"><font color="#660000"><u>Continental Army</u></font></a> in the spring of 1783. According to Private <a href="javascript:person(&apos;thomas_foster&apos;)"><font color="#660000"><u>Thomas Foster&apos;s</u></font></a> diary, two questions seemed to be on every soldier&apos;s lips: &quot;when do you expect to be discharged and go home and be rid of this army&quot;? and, &quot;how we are to be paid off&quot;? </p><br><p><b>An Ungrateful Nation</b><br>Despite the rumors, the year wore on with neither <a href="javascript:glossary(&apos;discharge&apos;)"><font color="#660000"><u>discharge</u></font></a> nor pay in sight. An ungrateful nation once again turned a cold shoulder to the soldiers whose sacrifices had preserved it time and time again from disaster. Soldiers frustrated by Congress&apos; continuing refusal to either discharge or pay them, chafed under army discipline. Anonymous letters urged officers to hold Congress to the promises it had made to pay officers half pay <a href="javascript:glossary(&apos;pension&apos;)"><font color="#660000"><u>pensions</u></font></a> for life once the war ended. Personal appeals by General Washington kept matters in check, but morale and relations between enlisted men and officers continued to deteriorate. </p><br><p><b>Useless Scrip</b><br>Most soldiers received <a href="javascript:glossary(&apos;furlough&apos;)"><font color="#660000"><u>furloughs</u></font></a> instead of the long awaited and longed-for discharges. The single month of pay the Congress grudgingly paid each man fell disgracefully short of the years of back pay it owed. The government <a href="javascript:glossary(&apos;scrip&apos;)"><font color="#660000"><u>scrip</u></font></a> the soldiers received for the remainder of their pay was of little use to those in desperate need of ready money for themselves and their families. Many men traded their certificates for goods or cash at a fraction of their face value. Some sold their <a href="javascript:artifact(&apos;charleville_musket&apos;)"><font color="#660000"><u>muskets</u></font></a> and other possessions. </p><br><p><b>A Bitter Betrayal</b><br>Congress discharged the army, including the few remaining Massachusetts and Connecticut regiments at <a href="javascript:artifact(&apos;west_point&apos;)"><font color="#660000"><u>West Point</u></font></a>, New York, through the fall of 1783. The joy soldiers experienced at returning home to familiar scenes and loved ones was offset by poverty and a bitter sense of betrayal by a government and people who had failed them.</p><br>'];
  rollTexts["hugh_maxwell"] = ['<b>A Final Exchange</b>','Lt. Colonel Hugh Maxwell of Charlemont, Massachusetts, buys government certificates from a soldier in his regiment who is in immediate need of cash. (Click for more)'];
	rollLinks["hugh_maxwell"] = ['person','hugh_maxwell',''];
		rollTexts["thomas_foster"] = ['<b>Deceived and Destitute</b>','In his journal, Private Thomas Foster writes of enlisted men&apos;s anger at being sent &quot;into the country naked and destitute of money&quot; and their belief that their country has &quot;most shamefully deceived and baffled&quot; them. (Click for more)'];
	rollLinks["thomas_foster"] = ['person','thomas_foster',''];
		rollTexts["john_chaloner"] = ['<b>A Long Journey</b>','John Chaloner of Greenfield eagerly takes the first steps of his long journey back to Greenfield, Massachusetts. (Click for more)'];
	rollLinks["john_chaloner"] = ['person','john_chaloner',''];
		rollTexts["moses_sash"] = ['<b>Final Preparations</b>','Moses Sash of Worthington gathers his things and prepares to return home to Massachusetts. (Click for more)'];
	rollLinks["moses_sash"] = ['person','moses_sash',''];
		rollTexts["washer_woman"] = ['<b>Duties Done</b>','Female non-combatants have been part of the daily life of the army throughout the long war. This washerwoman prepares to leave West Point as the last regiments disband.'];
	rollTexts["civilian"] = ['<b>A Civilian Once More</b>','This man already has exchanged his torn and threadbare uniform for civilian clothing.'];
	rollTexts["pot_iron"] = ['<b>Worth Keeping</b>','Eight-year army veteran Thomas Foster carried this kettle on campaign; now he carries it home to Barnstable, Massachusetts. (Click for more)'];
	rollLinks["pot_iron"] = ['artifact','pot_iron',''];
		rollTexts["charleville_musket"] = ['<b>Quick Cash</b>','A soldier sells his flintlock for quick cash. (Click for more)'];
	rollLinks["charleville_musket"] = ['artifact','charleville_musket',''];
		rollTexts["tricorn_hat"] = ['<b>Civilian and Military Wear</b>','Hats are part of daily wear for all men. The tricorn is a popular civilian as well as military style. (Click for more)'];
	rollLinks["tricorn_hat"] = ['artifact','tricorn_hat',''];
		rollTexts["drum"] = ['<b>Among the Last </b>','Both the drum he is allowed to carry home and the reversed colors on his uniform coat identify this soldier as a musician. (Click for more)'];
	rollLinks["drum"] = ['artifact','drum',''];
		rollTexts["west_point"] = ['<b>Long Barracks</b>','The stone barracks at West Point are far superior to the living conditions soldiers experienced throughout the Revolutionary War.  (Click for more)'];
	rollLinks["west_point"] = ['artifact','west_point',''];
		rollTexts["brown_bess"] = ['<b>Final Volley</b>','Before disbanding, a company fires a final volley to honor a popular officer.  (Click for more)'];
	rollLinks["brown_bess"] = ['artifact','brown_bess',''];
		rollTexts["cartridge_box"] = ['<b>Cartridge Papers</b>','Used cartridge papers litter the ground in front of the soldiers firing a final salute.  (Click for more)'];
	rollLinks["cartridge_box"] = ['artifact','cartridge_box',''];
		rollTexts["chevron"] = ['<b>Badge of Honor</b>','Only enlisted men with at least three years of service, and who have shown &quot;bravery, fidelity and good conduct,&quot; are permitted to wear the white chevron this man proudly displays on his tattered uniform coat.'];
	rollTexts["shoe_repair"] = ['<b>Emergency Repairs</b>','Unable to afford new footwear, John Chaloner hopes some strategically-wrapped string will keep his shoes from falling apart.'];
	rollTexts["certificate"] = ['<b>Badge of Ill-treatment </b>','Some men angrily display in their hats the practically worthless government certificates they have received as pay in place of cash.'];
	rollTexts["sutler"] = ['<b>Brisk Business</b>','This civilian sutler sold food and supplies to soldiers during the war. Now he does a brisk business purchasing their muskets, government certificates and other possessions in exchange for food and much-needed cash. '];
	rollTexts["notes"] = ['<b>Promises to Pay</b>','Congress scrapes together one month&apos;s pay in cash for the army. Officers and soldiers receive the remainder of what they are owed in interest-bearing government certificates. '];
	rollTexts["tattered"] = ['<b>Hard Usage</b>','Buttonless, tailess, ragged and hopelessly stained uniforms testify to the hardships the army has endured.  '];
	rollTexts["firewood"] = ['<b>Final Chore</b>','Joseph Plum Martin of Connecticut carries wood, part of the two cords of firewood he was ordered to split and stack before being discharged.   '];
	
